version: '3.8'

services:
  user-service:
    image: docker.io/paumicsul/user-service:${IMAGE_TAG}
    ports:
      - "8081:8081"
    restart: always

  crime-service:
    image: docker.io/paumicsul/crime-service:${IMAGE_TAG}
    ports:
      - "8082:8082"
    restart: always

  location-service:
    image: docker.io/paumicsul/location-service:${IMAGE_TAG}
    ports:
      - "8083:8083"
    restart: always

  discovery-server:
    image: docker.io/paumicsul/discovery-server:${IMAGE_TAG}
    ports:
      - "8761:8761"
    restart: always

  api-gateway:
    image: docker.io/paumicsul/api-gateway:${IMAGE_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - crime-service
      - location-service
      - discovery-server
    restart: always
